//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/MsgId.proto
namespace proto.MsgId
{
    [global::ProtoBuf.ProtoContract(Name=@"MsgId")]
    public enum MsgId
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"None", Value=0)]
      None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgMove", Value=1)]
      MsgMove = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgAttack", Value=2)]
      MsgAttack = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPing", Value=3)]
      MsgPing = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MsgPong", Value=4)]
      MsgPong = 4
    }
  
}